version: '2.3'

services:

  vueling-server:
    image: vueling-server
    container_name: vueling-server
    working_dir: /data
    build:
      context: ../
      dockerfile: docker/Dockerfile

    environment:
      - PYTHONPATH=/data
    ports:
      - 5000:5000
    volumes:
      - ../:/data
    command: tail /dev/null -f
  frontend:
    image: react
    container_name: frontend
    build:
      context: .
      dockerfile: ./Dockerfile_frontend
    volumes:
      - '../frontend:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
